euphorbia/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from euphorbia import settings
from euphorbia.views import home, logout_view, anonymous_required
from django.contrib.auth import views



urlpatterns = patterns('',
        url(r'^$', RedirectView.as_view(url='/platform/login/')),
        url(r'^logout/$', logout_view),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^platform/', include('platform.urls', namespace="platform")),
        url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/logos/favicon.ico'))
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platform/urls.py
from django.conf.urls import patterns, url
from euphorbia.views import anonymous_required
from platform.views.adspots import OneAdspotView, CreateAdspotView
from platform.views.banners import CreateBannerView
from platform.views.campaigns import CampaignsView, CreateCampaignView, OneCampaignView
from platform.views.other import tracking, tracking_ajax, profile, logout_view, register
from platform.views.register import RegisterView
from django.contrib.auth import views
from django.views.generic import RedirectView
from platform.views.sites import SitesView, OneSiteView, CreateSiteView
from platform.views.publisher_stats import test_view

__author__ = 'igorzygin'


urlpatterns = patterns('',
        url(r'^$', RedirectView.as_view(url='login/')),
        url(r'^profile/', profile),

        url(r'^tracking/', tracking),
        url(r'^tracking_ajax/', tracking_ajax),

        url(r'^sites/create/$', CreateSiteView.as_view()),
        url(r'^sites/(?P<pk>\d+)/$', OneSiteView.as_view()),
        #url(r'^sites/', SitesView.as_view()),
        url(r'^sites/test/$', test_view),

        url(r'^adspots/create/$', CreateAdspotView.as_view()),
        url(r'^adspots/(?P<pk>\d+)/$', OneAdspotView.as_view()),

        url(r'^campaigns/create/$', CreateCampaignView.as_view()),
        url(r'^campaigns/(?P<pk>\d+)/$', OneCampaignView.as_view()),
        url(r'^campaigns/', CampaignsView.as_view()),

        url(r'^banner/create/$', CreateBannerView.as_view()),

        url(r'^advert/', tracking),

        url(r'^register/',  anonymous_required(RegisterView.as_view())),
        url(r'^login/', anonymous_required(views.login), {"template_name": "registration/login.html"}),
        url(r'^logout/', logout_view),
        url(r'^register/', register)
    )

platform/models.py
from datetime import datetime
import uuid
from django.db import models
from users.models import User
from  django.contrib.postgres.fields import ArrayField
__author__ = 'igorzygin'

def generate_unique_code():
    return uuid.uuid4().hex[:15].upper()


class AdThematics(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, blank=False)


class AdFormat(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, blank=False)


class UserSite(models.Model):
    def __unicode__(self):
        return self.name+" "+self.url
    user = models.ForeignKey(User, unique=False)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    created = models.DateTimeField(default=datetime.now)
    thematics = models.ManyToManyField(AdThematics, blank=True)


class UserPixel(models.Model):
    def __unicode__(self):
        return self.name+" "+self.unique_code
    site = models.ForeignKey(UserSite, unique=False)
    name = models.CharField(max_length=100, unique=True)
    unique_code = models.CharField(max_length=300, unique=True, default=generate_unique_code)


class AdSpot(models.Model):
    def __unicode__(self):
        return self.name+" "+self.unique_code
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, unique=True)
    unique_code = models.CharField(max_length=300, unique=True, default=generate_unique_code)
    site = models.ForeignKey(UserSite)
    format = models.ManyToManyField(AdFormat, max_length=3, blank=False)

    def html_code(self):
        return self.unique_code


class Campaign(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, unique=True)
    user = models.ForeignKey(User, unique=False)
    thematics = models.ManyToManyField(AdThematics, blank=True)


class Banner(models.Model):
    def __unicode__(self):
        return self.campaign.name+" "+str(self.id)+" "+str(self.format)
    created = models.DateTimeField(default=datetime.now)
    campaign = models.ForeignKey(Campaign)
    image = models.ImageField(upload_to='b/')
    format = models.ForeignKey(AdFormat, blank=False, null=False)
    url = models.CharField(max_length=255, blank=False, null=False)

    def get_image_link(self):
        return '/media/%s' % self.image

platform/views.py
# -*- coding: utf-8 -*-
import json
from django.contrib.auth import logout

from django.db import connection
from django.shortcuts import render


# Create your views here.
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.template import RequestContext
from platform.models import UserSite, UserPixel



#
#   -||-||-||-||-||-
#    PLATFORM VIEWS
#   -||-||-||-||-||-
#


#
#   Вход, регистрация и т.п.
#
#   Страница входа, login. => django.contrib.auth.views.login
#


#
#   Страница регистрации
#
def register(request):
    return render_to_response("register.html")


#
#   Выход
#
def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")

#
#   Страница профиля
#
@login_required
def profile(request):
    return HttpResponseRedirect("/platform/tracking/")


#
#   Обработка данных трекинга
#
#   Страница трекинга.
#
@login_required
def tracking(request):
    # Данные для меню
    left_menu_data = get_menu(request)
    left_menu_links = get_menu_links(request)

    # Данные для тулбара
    toolbar_dates = get_toolbar_dates(request)

    # Данные для таблицы
    treetable_data, sp_id_data = get_sites(request)

    # Данные для графика показов
    views_chart_data = get_views_data(treetable_data[0]["spID"], None)
    #views_chart_axis_steps = get_views_steps(views_chart_data, ["views", "reqs"])

    # Данные для графика времени посещений
    time_chart_data = get_time_data(treetable_data[0]["spID"], None)
    #time_chart_axis_steps = get_views_steps(time_chart_data, ["active", "total"])

    # Ликвидация экранирования
    left_menu_data = json.dumps(left_menu_data)
    left_menu_links = json.dumps(left_menu_links)
    toolbar_dates = json.dumps(toolbar_dates)
    treetable_data = json.dumps(treetable_data)
    views_chart_data = json.dumps(views_chart_data)
    #views_chart_axis_steps = json.dumps(views_chart_axis_steps)
    time_chart_data = json.dumps(time_chart_data)
    #time_chart_axis_steps = json.dumps(time_chart_axis_steps)

    context = {
        "left_menu_data": left_menu_data,
        "left_menu_links": left_menu_links,
        "toolbar_dates": toolbar_dates,
        "treetable_data": treetable_data,
        "sp_id_data": sp_id_data,
        #"views_chart_axis_steps": views_chart_axis_steps,
        #"time_chart_axis_steps": time_chart_axis_steps,
        "views_chart_data": views_chart_data,
        "time_chart_data": time_chart_data
        }
    return render_to_response("tracking.html", context, context_instance=RequestContext(request))


#
#   Обработка AJAX приходящих с tracking.
#
def tracking_ajax(request):
    command = request.GET.get("command")
    return JsonResponse(get_command(command)(request))

def get_command(com):
    return {
        "get_data_by_sp_id": get_site_data,
        "get_refresh_data": get_refresh_data
    }.get(com)

#
#   Получить данные выбранного сайта/страницы (AJAX)
#
def get_site_data(request):

    # Данные для графика показов
    views_chart_data = get_views_data_request(request)
    #views_chart_axis_steps = get_views_steps(views_chart_data, ["views", "reqs"])

    # Данные для графика времени посещений
    time_chart_data = get_time_data_request(request)
    #time_chart_axis_steps = get_views_steps(time_chart_data, ["active", "total"])

    sp_name = get_sp_name(request)

    result = {
        "visitChartData": views_chart_data,
        #"visitChartYAxis": views_chart_axis_steps,
        "timeChartData": time_chart_data,
        #"timeChartYAxis": time_chart_axis_steps,
        "spName": sp_name
    }

    return result

#
#   Обработка "обновить" (AJAX)
#
def get_refresh_data(request):

    views_time_data = get_site_data(request)
    treetable_data, sp_id_data = get_sites(request)

    views_time_data["trackTreetableData"] = treetable_data
    views_time_data["spIDData"] = sp_id_data
    views_time_data["toolbarDates"] = get_toolbar_dates(request)

    return views_time_data


#
#   Формирование списка для выбора дат
#
def get_toolbar_dates(request):
    return ["Сегодня", "Вчера", "Октябрь", "Сентябрь"]


#
#   Получение списка сайтов и пикселей для treetable
#
def get_sites(request):
    sites_list = UserSite.objects.filter(user=request.user)

    result_data = []
    sp_data_map = {}

    data = []
    site_counter = 1
    is_open = True

    for site in sites_list:
        pixel_list = site.userpixel_set.all()
        pixels_data = []

        if len(pixel_list) != 0:
            pixel_map = {pixel.unique_code: pixel for pixel in pixel_list}
            pixel_code_list = [pixel.unique_code for pixel in pixel_list]
            pixel_code_list_str = "'%s'" % ("', '".join(pixel_code_list))

            query = "SELECT page_unique_code, median(coalesce(active_time, 0)) as active, median(EXTRACT(EPOCH from (coalesce(session_updated, created) - created))) AS total, count(session_id) as visits, count(DISTINCT local_user_id) as unique_visits \
                        FROM page_sessions_link \
                        WHERE os != 'NULL' AND browser  != 'NULL' AND page_unique_code in (%s) \
                        GROUP BY page_unique_code \
                        ORDER BY page_unique_code" % pixel_code_list_str

            data = get_data_from_sql(query)

            pixel_counter = 1

            is_open = len(data)
            if (is_open):
                for entry in data:
                    pixel = pixel_map[entry["page_unique_code"]]
                    pixel_entry = {"id": str(site_counter) + "." + str(pixel_counter),
                                   "value": pixel.name + " (" + pixel.unique_code + ")", "time": time_presentation(entry["total"], " сек."),
                                   "active": time_presentation(entry["active"], " сек."),
                                   "visits": entry["visits"], "uniq": entry["unique_visits"], "spID": pixel.id}
                    pixels_data.append(pixel_entry)
                    sp_data_map[str(site_counter) + "." + str(pixel_counter)] = pixel.id;
                    pixel_counter += 1
            else:
                for entry in pixel_list:
                    pixel = entry
                    pixel_entry = {"id": str(site_counter) + "." + str(pixel_counter),
                                   "value": pixel.name + " (" + pixel.unique_code + ")", "time": "0 сек.",
                                   "active": "0 сек.", "visits": 0, "uniq": 0, "spID": pixel.id}
                    pixels_data.append(pixel_entry)
                    sp_data_map[str(site_counter) + "." + str(pixel_counter)] = pixel.id;
                    pixel_counter += 1

            site_active = time_presentation(sum([entry["active"] for entry in data]) / len(data) if len(data) > 0 else 0, " сек.")
            site_time = time_presentation(sum([entry["total"] for entry in data]) / len(data) if len(data) > 0 else 0, " сек.")
            site_visits = sum([entry["visits"] for entry in data])
            site_unique_visits = sum([entry["unique_visits"] for entry in data])
        else:
            site_active = "0 сек."
            site_time = "0 сек."
            site_visits = 0
            site_unique_visits = 0

        site_data = {"id": str(site_counter), "value": site.name, "time": site_time, "active": site_active,
                     "visits": site_visits, "uniq": site_unique_visits, "open": is_open, "data": pixels_data,
                     "spID": site.id}
        result_data.append(site_data)
        sp_data_map[str(site_counter)] = site.id;
        site_counter += 1
    return result_data, sp_data_map


#
#   Имя сайта-пикселя по данным из запроса
#
def get_sp_name(request):
    site_id = request.GET["site_id"] if "site_id" in request.GET else None
    page_id = request.GET["page_id"] if "page_id" in request.GET else None
    if site_id is not None:
        return UserSite.objects.get(pk=site_id).name
    else:
        return UserPixel.objects.get(pk=page_id).name

#
#   Получение данных показов (request)
#
def get_views_data_request(request):
    site_id = request.GET["site_id"] if "site_id" in request.GET else None
    page_id = request.GET["page_id"] if "page_id" in request.GET else None
    return get_views_data(site_id, page_id)

#
#   Получение данных показов (site_id, page_id)
#
def get_views_data(site_id, page_id):
    result_data = []
    pixel_code_list = []
    if site_id is not None:
        site = UserSite.objects.get(pk=site_id)
        pixel_list = site.userpixel_set.all()
        pixel_code_list = [pixel.unique_code for pixel in pixel_list]
    else:
        pixel = UserPixel.objects.get(pk=page_id)
        pixel_code_list = [pixel.unique_code]
    pixel_code_list_str = "'%s'" % ("', '".join(pixel_code_list))
    query = "SELECT date(created) as date, count(session_id) as visits, count(DISTINCT local_user_id) as unique_visits \
                    FROM page_sessions_link \
                    WHERE os != 'NULL' AND browser  != 'NULL' AND page_unique_code in (%s) \
                    GROUP BY date(created) \
                    ORDER BY date(created)" % pixel_code_list_str
    data = get_data_from_sql(query)

    counter = 0
    for entry in data:
        result_data.append({"id": counter, "views": entry["visits"], "reqs": entry["unique_visits"], "xAxis": str(entry["date"])})
        counter += 1
    # return [{"views": entry["visits"], "reqs": entry["unique_visits"], "xAxis": idx} for idx, entry in data]
    return result_data


#
#   Получение данных времени (request)
#
def get_time_data_request(request):
    site_id = request.GET["site_id"] if "site_id" in request.GET else None
    page_id = request.GET["page_id"] if "page_id" in request.GET else None
    return get_time_data(site_id, page_id)

#
#   Получение данных времени (site_id, page_id)
#
def get_time_data(site_id, page_id):
    result_data = []
    pixel_code_list = []

platform/views/campaigns.py
import json
from django import forms
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView, ListView
from platform.models import UserSite, AdSpot, AdThematics, Campaign
from platform.views.sites import LoginRequiredMixin

__author__ = 'igorzygin'




class CampaignsView(LoginRequiredMixin, ListView):
    template_name = "campaigns_list.html"
    context_object_name = 'campaigns_list'

    def get_queryset(self):
        return Campaign.objects.filter(user=self.request.user)

# `
class OneCampaignView(LoginRequiredMixin, TemplateView):
    template_name = 'campaign_one.html'

    def get_context_data(self, **kwargs):
        pk=self.kwargs['pk']
        data = super(OneCampaignView, self).get_context_data(**kwargs)
        data['campaign'] = Campaign.objects.get(pk=pk, user=self.request.user)
        return data
#
#
#
class CreateCampaignView(LoginRequiredMixin, FormView):
    template_name = 'campaign_create.html'


    def get_thematics(self):
        return AdThematics.objects.all()


    def get(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        return self.render_to_response({"form": CampaignForm(), "thematics_choice":self.get_thematics()})

    def post(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        form = CampaignForm(request.POST)
        print request.POST
        if form.is_valid():
            campaign=Campaign.objects.create(user=request.user, name=form.cleaned_data['name'])
            campaign.thematics=form.cleaned_data['thematics']
            campaign.save()
            return HttpResponseRedirect("/platform/campaigns/")
        else:
            return self.render_to_response({"form": form, "thematics_choice":self.get_thematics()})

class CampaignForm(forms.ModelForm):
     class Meta:
        fields = ['name', 'thematics']
        model = Campaign


#
#
# def get_sites(request):
#     sites = UserSite.objects.filter(user=request.user)
#     return json.dumps(sites)
#
# def get_adspots_by_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#
# def create_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#

platform/templates/adspot_create.html
{% block content %}
 <section>
    <form method="post" action="">
        {% csrf_token %}
        <input name="name" type="text" value="{{form.name.value|default_if_none:""}}"><br>
        {{form.name.errors}}<br>
        <select name="site">
            {% for site in site_choice %}
                <option value="{{site.id}}" {%if site.id == form.site.value.id%}selected{%endif%}>{{site.name}}</option>
            {% endfor %}
        </select><br>
        {{form.site.errors}}<br>
        <select multiple name="format">
            {% for format in format_choice %}
                <option value="{{format.id}}" {%if format.id|stringformat:"i" in form.format.value%}selected{%endif%}>{{format.name}}</option>
            {% endfor %}
        </select><br>
        <!--<input name="thematics" type="text" value="{{form.thematics.value}}">-->
        {{form.format.errors}}
        <input type="submit" value="Submit">
    </form>
 </section>
{% endblock %}

platform/templates/adspot_one.html
{% block content %}
 <section ng-app="siteApp">
                <span>ID</span>
                <span>{{adspot.id}}</span><br>
                <span>Создано</span>
                <span>{{adspot.created}}</span><br>
                <span>Имя</span>
                <span>{{adspot.name}}</span><br>
                <span>Форматы </span>
                <span>{% for format in adspot.format.all %}{{format.name}}{% endfor %}</span>
                <span>HTML-code</span>
                <span>{{adspot.html_code}}</span>
 </section>

{% endblock %}

platform/templates/banner_create.html
{% block content %}
 <section>
    <form method="post" action="" enctype="multipart/form-data" >
        {% csrf_token %}
        <input name="url" type="text" value="{{form.url.value|default_if_none:""}}"><br>
        {{form.url.errors}}<br>
        <select name="campaign">
            {% for campaign in campaign_choice %}
                <option value="{{campaign.id}}" {%if campaign.id == form.campaign.value.id%}selected{%endif%}>{{campaign.name}}</option>
            {% endfor %}
        </select><br>
        {{form.campaign.errors}}<br>
        <select name="format">
            {% for format in format_choice %}
                <option value="{{format.id}}" {%if format.id == form.format.value.id%}selected{%endif%}>{{format.name}}</option>
            {% endfor %}
        </select><br>
        {{form.format.errors}}<br>
        <input type="file" name="image" accept="image/*,image/jpeg">
        {{form.image.errors}}<br>
        <input type="submit" value="Submit">
    </form>
 </section>
{% endblock %}

platform/templates/campaign_create.html
{% block content %}
 <section>
    <form method="post" action="">
        {% csrf_token %}
        <input name="name" type="text" value="{{form.name.value|default_if_none:""}}"><br>
        {{form.name.errors}}<br>
        <select multiple name="thematics">
            {% for them in thematics_choice %}
                <option value="{{them.id}}" {%if them.id in form.thematics.value%}selected{%endif%}>{{them.name}}</option>
            {% endfor %}
        </select><br>
        <!--<input name="thematics" type="text" value="{{form.thematics.value}}">-->
        {{form.thematics.errors}}
        <input type="submit" value="Submit">
    </form>
 </section>
{% endblock %}

platform/templates/campaigns_list.html
{% extends "ui-base.html" %}
{% block title %}Кампании{% endblock %}


{% block css %}

    <!-- webix.css -->
    <link href="/static/libs/webix/codebase/webix.css" rel="stylesheet" type="text/css" >

	<!-- tracking.css -->
    <link href="/static/css/tracking.css" rel="stylesheet" type="text/css" >

	<!--left-menu.css-->
	<link href="/static/css/left-menu.css" rel="stylesheet" type="text/css" >

{% endblock %}
{% block js %}

	<!-- jQuery -->
	<script src="/static/libs/jquery-2.1.4.min.js"></script>

    <!-- left_menu.js -->
    <script src="/static/js/left_menu.js"></script>

    <!-- Webix JS Core -->
    <script src="/static/libs/webix/codebase/webix.js"></script>

{% endblock %}



{% block menu %}<div class="tracking-menu-inner-div" id="leftMenuContainerInner"></div>{% endblock %}
{% block content %}
 <section ng-app="siteApp">
    <table>
        <thead>
        <td>ID</td><td>Имя</td><td>Количество баннеров</td><td>Ссылка</td>
        </thead>
        {% for campaign in campaigns_list %}
            <tr>
                <td>{{campaign.id}}</td>
                <td>{{campaign.name}}</td>
                <td>{{campaign.banner_set.all | length}}</td>
                <td><a href="{{campaign.id}}/">Подробнее</a></td>
            </tr>
        {% endfor %}
    </table>
     <a href="create/">Создать новую кампанию</a>
 </section>

{% endblock %}

platform/templates/lr-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

	<head>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">

		<title>{% block title %}{% endblock %}</title>

		<!-- lr-base.css -->
		<link href="/static/css/lr-base.css" rel="stylesheet" type="text/css" >

		{% block css %}
		{% endblock %}

		{% block js %}
		{% endblock %}


	</head>

	<body>

        <div class="lr-div">
            {% block content %}{% endblock %}
        </div>

	<script>{% block webix_code %}{% endblock %}</script>

    </body>

</html>

platform/templates/publisher.html
{% extends "ui-base.html" %}
{% block title %}Трекинг{% endblock %}


{% block css %}
<!-- webix.css -->
<link href="/static/libs/webix/codebase/webix.css" rel="stylesheet" type="text/css">

<!-- Date Range Picker -->
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

<!-- tracking.css -->
<link href="/static/css/tracking.css" rel="stylesheet" type="text/css">

<!--left-menu.css-->
<link href="/static/css/left-menu.css" rel="stylesheet" type="text/css">

{% endblock %}


{% block js %}

<!-- jQuery -->
<script src="/static/libs/jquery-2.1.4.min.js"></script>

<!-- Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>

<!-- tracking.js -->
<script src="/static/js/tracking.js"></script>

<!-- build_tracking_webix_ui.js -->
<script src="/static/js/build_tracking_webix_ui.js"></script>

<!-- left_menu.js -->
<script src="/static/js/left_menu.js"></script>

<!-- build_calendar.js -->
<script src="/static/js/build_calendar.js"></script>

<!-- Webix JS Core -->
<script src="/static/libs/webix/codebase/webix.js"></script>

{% endblock %}

{% block webix_data %}

var menuData = {

	"leftMenuData": {{ left_menu_data|safe }},
	"leftMenuLinks": {{ left_menu_links|safe }}

};

var contentData = {

	"pubTreetableData": {{ treetable_data|safe }}

};

{% endblock %}


{% block menu %}<div class="tracking-menu-inner-div" id="leftMenuContainerInner"></div>{% endblock %}


{% block content %}
<div class="tracking-content-top-inner-div" id="contentContainerInnerTop">
    <div class="tracking-content-top-inner-div-calendar" id="contentContainerInnerTopCalendar">
        <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; border-radius: 5px; width: auto">
            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>&nbsp;
            <span></span> <b class="caret"></b>
        </div>
    </div>
    <div class="tracking-content-top-inner-div-webix" id="contentContainerInnerTopWebix"></div>
</div>
<div class="tracking-content-inner-div" id="contentContainerInner"></div>
{% endblock %}


{% block js_code %}

    tracking({{ from_date|safe }}, {{ to_date|safe }});

{% endblock %}

platform/templates/register.html
{% extends "lr-base.html" %}
{% block title %}Регистрация{% endblock %}


{% block css %}

    <!-- webix.css -->
    <link href="/static/libs/webix/codebase/webix.css" rel="stylesheet" type="text/css" >

    <!--login.css-->
	<link href="/static/css/login.css" rel="stylesheet" type="text/css" >

{% endblock %}


{% block js %}

    <!-- Webix JS Core -->
    <script src="/static/libs/webix/codebase/webix.js"></script>

    <!-- Webix JS Core -->
    <script src="/static/js/login_form.js"></script>

    <!-- jQuery -->
	<script src="/static/libs/jquery-2.1.4.min.js"></script>

{% endblock %}


{% block content %}
<h1>REGISTRATION</h1>
     {{form.non_field_errors}}
    <form method="POST" action="">
        {% csrf_token %}
        <div>
        <span>EMAIL *</span><br>
        <input type="email" id="email" name="email" value="{{form.email.value|default_if_none:""}}"><br>
        {{ form.email.errors }}
        </div><br>
        <div>
        <span>PASSWORD *</span><br>
        <input type="password" id="password" name="password" value=""><br>
        {{ form.password.errors }}
        </div><br>
        <div>
        <span>PHONE *</span><br>
        <input type="text" id="phone" name="phone" value="{{form.phone.value|default_if_none:""}}"><br>
        {{ form.phone.errors }}
        </div><br>
        <div>
        <span>TYPE *</span><br>
        <select name="role">
            <option value="0"  {% if form.cleaned_data.role != 1 %} selected {% endif %}>Advertiser</option>
            <option value="1" {% if form.cleaned_data.role == 1 %} selected {% endif %}>Publisher</option>
        </select><br>
        {{ form.role.errors }}
        </div><br>
        <input type="submit" value="ЗАРЕГИСТРИРОВАТЬСЯ">
    </form>
{% endblock %}


{% block webix_code %}
{% endblock %}
>>>>>>> 75967e60191c4d604068c66daf84986ae9e9f3be

platform/templates/register_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>REGISTRATION FAILED TRY LATER</h1>
</body>
</html>

platform/templates/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>REGISTRATION SUCCESSFUL</h1>
</body>
</html>

platform/templates/sites_list.html
{% block content %}
 <section ng-app="siteApp">
    <table>
        <thead>
        <td>ID</td><td>Имя</td><td>Количество баннеров</td><td>Ссылка</td>
        </thead>
        {% for site in sites_list %}
            <tr>
                <td>{{site.id}}</td>
                <td>{{site.name}}</td>
                <td>{{site.banner_set.all | length}}</td>
                <td><a href="{{site.id}}/">Подробнее</a></td>
            </tr>
        {% endfor %}
    </table>
     <a href="create/">Создать новый сайт</a>
 </section>

{% endblock %}