euphorbia/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from euphorbia import settings
from euphorbia.views import home, logout_view, anonymous_required
from django.contrib.auth import views



urlpatterns = patterns('',
        url(r'^$', RedirectView.as_view(url='/platform/login/')),
        url(r'^logout/$', logout_view),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^platform/', include('platform.urls', namespace="platform")),
        url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/logos/favicon.ico'))
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platform/urls.py
from django.conf.urls import patterns, url
from euphorbia.views import anonymous_required
from platform.views.adspots import OneAdspotView, CreateAdspotView
from platform.views.banners import CreateBannerView
from platform.views.campaigns import CampaignsView, CreateCampaignView, OneCampaignView
from platform.views.other import tracking, tracking_ajax, profile, logout_view, register
from platform.views.register import RegisterView
from django.contrib.auth import views
from django.views.generic import RedirectView
from platform.views.sites import SitesView, OneSiteView, CreateSiteView
from platform.views.publisher_stats import test_view

__author__ = 'igorzygin'


urlpatterns = patterns('',
        url(r'^$', RedirectView.as_view(url='login/')),
        url(r'^profile/', profile),

        url(r'^tracking/', tracking),
        url(r'^tracking_ajax/', tracking_ajax),

        url(r'^sites/create/$', CreateSiteView.as_view()),
        url(r'^sites/(?P<pk>\d+)/$', OneSiteView.as_view()),
        #url(r'^sites/', SitesView.as_view()),
        url(r'^sites/test/$', test_view),

        url(r'^adspots/create/$', CreateAdspotView.as_view()),
        url(r'^adspots/(?P<pk>\d+)/$', OneAdspotView.as_view()),

        url(r'^campaigns/create/$', CreateCampaignView.as_view()),
        url(r'^campaigns/(?P<pk>\d+)/$', OneCampaignView.as_view()),
        url(r'^campaigns/', CampaignsView.as_view()),

        url(r'^banner/create/$', CreateBannerView.as_view()),

        url(r'^advert/', tracking),

        url(r'^register/',  anonymous_required(RegisterView.as_view())),
        url(r'^login/', anonymous_required(views.login), {"template_name": "registration/login.html"}),
        url(r'^logout/', logout_view),
        url(r'^register/', register)
    )

platform/models.py
from datetime import datetime
import uuid
from django.db import models
from users.models import User
from  django.contrib.postgres.fields import ArrayField
__author__ = 'igorzygin'

def generate_unique_code():
    return uuid.uuid4().hex[:15].upper()


class AdThematics(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, blank=False)


class AdFormat(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, blank=False)


class UserSite(models.Model):
    def __unicode__(self):
        return self.name+" "+self.url
    user = models.ForeignKey(User, unique=False)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    created = models.DateTimeField(default=datetime.now)
    thematics = models.ManyToManyField(AdThematics, blank=True)


class UserPixel(models.Model):
    def __unicode__(self):
        return self.name+" "+self.unique_code
    site = models.ForeignKey(UserSite, unique=False)
    name = models.CharField(max_length=100, unique=True)
    unique_code = models.CharField(max_length=300, unique=True, default=generate_unique_code)


class AdSpot(models.Model):
    def __unicode__(self):
        return self.name+" "+self.unique_code
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, unique=True)
    unique_code = models.CharField(max_length=300, unique=True, default=generate_unique_code)
    site = models.ForeignKey(UserSite)
    format = models.ManyToManyField(AdFormat, max_length=3, blank=False)

    def html_code(self):
        return self.unique_code


class Campaign(models.Model):
    def __unicode__(self):
        return self.name
    created = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=100, unique=True)
    user = models.ForeignKey(User, unique=False)
    thematics = models.ManyToManyField(AdThematics, blank=True)


class Banner(models.Model):
    def __unicode__(self):
        return self.campaign.name+" "+str(self.id)+" "+str(self.format)
    created = models.DateTimeField(default=datetime.now)
    campaign = models.ForeignKey(Campaign)
    image = models.ImageField(upload_to='b/')
    format = models.ForeignKey(AdFormat, blank=False, null=False)
    url = models.CharField(max_length=255, blank=False, null=False)

    def get_image_link(self):
        return '/media/%s' % self.image

platform/views/banners.py
# -*- coding: utf-8 -*-

import json
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView
from platform.models import UserSite, AdSpot, AdThematics, AdFormat, Campaign, Banner
from platform.views.other import get_data_from_sql
from platform.views.sites import LoginRequiredMixin

__author__ = 'igorzygin'

# def validate_adspot_name(value):
#     if len(AdSpot.objects.filter(name=value))>0:
#         raise ValidationError('%s must be unique' % value)
#
# class OneAdspotView(LoginRequiredMixin, TemplateView):
#     template_name = 'adspot_one.html'
#
#     def get_context_data(self, **kwargs):
#         pk=self.kwargs['pk']
#         data = super(OneAdspotView, self).get_context_data(**kwargs)
#         data['adspot'] = AdSpot.objects.get(pk=pk, site__user=self.request.user)
#         print data['adspot']
#         return data

#
#
class CreateBannerView(LoginRequiredMixin, FormView):
    template_name = 'banner_create.html'

    def get_format(self, request):
        return AdFormat.objects.all()

    def get_campaign(self, request):
        return Campaign.objects.filter(user=request.user)


    def get(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        return self.render_to_response({"form": BannerForm(), "format_choice":self.get_format(request), "campaign_choice":self.get_campaign(request)})

    def post(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        print request.FILES
        form = BannerForm(request.POST, request.FILES)
        print request.POST
        if form.is_valid():
            banner=Banner.objects.create(url=form.cleaned_data['url'], campaign=form.cleaned_data['campaign'], format=form.cleaned_data['format'], image=form.cleaned_data['image'])
            banner.save()
            return HttpResponseRedirect("/platform/campaigns/%d/" % banner.campaign.id)
        else:
            return self.render_to_response({"form": form, "format_choice":self.get_format(request), "campaign_choice":self.get_campaign(request)})
#
class BannerForm(forms.ModelForm):
    class Meta:
        fields = ['campaign','url','format','image']
        model = Banner


    def clean_image(self):
       image = self.cleaned_data.get("image")
       if not image:
           raise forms.ValidationError("No image!")
       else:

           req_width = 315
           req_height = 300
           if self.cleaned_data["format"].id == 1:
                req_width = 315
                req_height = 300
           elif self.cleaned_data["format"].id == 2:
                req_width = 300
                req_height = 250
           elif self.cleaned_data["format"].id == 3:
                req_width = 400
                req_height = 200
           w, h = get_image_dimensions(image)
           if w != req_width:
               raise forms.ValidationError("The image is %i pixel wide. It's supposed to be %i px" % (w, req_width))
           if h != req_height:
               raise forms.ValidationError("The image is %i pixel high. It's supposed to be %i px" % (h, req_height))
       return image
    # name = forms.CharField(max_length=100, required=True,validators=[validate_adspot_name])
    # site = forms.ModelChoiceField(queryset=UserSite.objects.all(), required=True)
    # format = forms.ModelMultipleChoiceField(queryset=AdFormat.objects.all(),required=True)

#


def get_campaign_stats(campaign_id_list):
    campaign_id_string = ','.join(campaign_id_list)
    query = 'select pc.id as campaign_id, CURRENT_DATE - s.a AS date, count(DISTINCT bss.id), count(DISTINCT bcc.id) \
            from platform_campaign as pc \
            inner join platform_banner as pb \
            on pb.campaign_id = pc.id \
            inner join \
            Generate_series(0, 30, 1) AS s(a) \
            On true \
            LEFT JOIN banner_show_stats as bss \
            ON date(bss.created)=CURRENT_DATE - s.a and bss.banner_id=pb.id \
            LEFT JOIN banner_clicks as bcc \
            On date(bcc.created)=CURRENT_DATE - s.a AND bcc.banner_id=pb.id \
            WHERE pc.id in (1,3) \
            GROUP BY pc.id, CURRENT_DATE - s.a;' % campaign_id_string
    data = get_data_from_sql(query)
    return data
# def get_sites(request):
#     sites = UserSite.objects.filter(user=request.user)
#     return json.dumps(sites)
#
# def get_adspots_by_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#
# def create_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#

platform/views/campaigns.py
import json
from django import forms
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView, ListView
from platform.models import UserSite, AdSpot, AdThematics, Campaign
from platform.views.sites import LoginRequiredMixin

__author__ = 'igorzygin'




class CampaignsView(LoginRequiredMixin, ListView):
    template_name = "campaigns_list.html"
    context_object_name = 'campaigns_list'

    def get_queryset(self):
        return Campaign.objects.filter(user=self.request.user)

# `
class OneCampaignView(LoginRequiredMixin, TemplateView):
    template_name = 'campaign_one.html'

    def get_context_data(self, **kwargs):
        pk=self.kwargs['pk']
        data = super(OneCampaignView, self).get_context_data(**kwargs)
        data['campaign'] = Campaign.objects.get(pk=pk, user=self.request.user)
        return data
#
#
#
class CreateCampaignView(LoginRequiredMixin, FormView):
    template_name = 'campaign_create.html'


    def get_thematics(self):
        return AdThematics.objects.all()


    def get(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        return self.render_to_response({"form": CampaignForm(), "thematics_choice":self.get_thematics()})

    def post(self, request, **kwargs):
        if request.user.is_anonymous():
            return HttpResponseRedirect("/")
        form = CampaignForm(request.POST)
        print request.POST
        if form.is_valid():
            campaign=Campaign.objects.create(user=request.user, name=form.cleaned_data['name'])
            campaign.thematics=form.cleaned_data['thematics']
            campaign.save()
            return HttpResponseRedirect("/platform/campaigns/")
        else:
            return self.render_to_response({"form": form, "thematics_choice":self.get_thematics()})

class CampaignForm(forms.ModelForm):
     class Meta:
        fields = ['name', 'thematics']
        model = Campaign


#
#
# def get_sites(request):
#     sites = UserSite.objects.filter(user=request.user)
#     return json.dumps(sites)
#
# def get_adspots_by_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#
# def create_site(request, pk):
#     site = UserSite.objects.filter(user=request.user, pk=pk)
#     adspots_list = site.adspot_set.all()
#     return json.dumps(adspots_list)
#
#

templates/banner_form.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block css %}
{% load humanize %}


{% endblock %}
{% block content %}
    <section style="padding-left: 15%;">
    <h1>Отправить заявку на создание баннера</h1>
    <form action="/banner/new/" method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.site_url.errors }}
            <label for="id_site_url">URL сайта:</label><br>
            {{ form.site_url }}
        </div>
        <div class="fieldWrapper">
            {{ form.banner_format.errors }}
            <label for="id_banner_format">Формат баннера:</label><br>
            {{ form.banner_format }}
        </div>
        <input type="submit" value="Отправить" class="btn btn-primary" />
    </form>
    </section>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>


    <!-- Webix CSS -->
    <link href="/static/webix/codebase/webix.css" rel="stylesheet" type="text/css" >

    <!-- DataView -->
    <link href="/static/webix/dataview.css" rel="stylesheet" type="text/css" >


    <link href="/static/bs/css/bootstrap.css" rel="stylesheet">

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
{#    <link href="/static/bs/css/bootstrap.readable.css" rel="stylesheet">#}

    <!-- Custom CSS -->
    <link href="/static/bs/css/freelancer.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bs/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block css %}
    {% endblock %}

    <!-- Webix JS Core -->
    <script src="/static/webix/codebase/webix.js"></script>

    <!-- jQuery Version 1.11.0 -->
    <script src="/static/bs/js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/bs/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="/static/bs/js/classie.js"></script>
    <script src="/static/bs/js/cbpAnimatedHeader.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="/static/bs/js/jqBootstrapValidation.js"></script>
{#    <script src="/static/bs/js/contact_me.js"></script>#}

    <!-- Custom Theme JavaScript -->
    <script src="/static/bs/js/freelancer.js"></script>

    <script src="http://cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
<script src="http://cdn.jsdelivr.net/momentjs/2.9.0/moment.min.js"></script>

<!-- Include Date Range Picker -->
<script src="http://cdn.jsdelivr.net/bootstrap.daterangepicker/1/daterangepicker.js"></script>

<link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/bootstrap.daterangepicker/1/daterangepicker-bs3.css" />
<script src="http://cdn.jsdelivr.net/bootstrap.daterangepicker/latest/daterangepicker.js"></script>


    {% block js %}
    {% endblock %}

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collap ese-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/#page-top">AdBox</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                {% if user and not user.is_anonymous %}
                     <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a href="/logout">Выйти</a>
                    </li>
                </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    </li>
                </ul>
                {%endif%}
                 <ul class="nav navbar-nav navbar">
                     <li class="page-scroll">
                            &nbsp;
                     </li>
                     <li class="page-scroll">
                            &nbsp;
                     </li>
                </ul>
                <ul class="nav navbar-nav navbar">
                     <li class="page-scroll">
                         <a href=""><i class="fa fa-phone"></i> +7 705-740-1880</a>
                     </li>
                     <li class="page-scroll">
                         <a class="" href="mailto:info@adbox.kz">info@adbox.kz</a>
                     </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>



    {% block content %}{% endblock %}


    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>Email</h3>
                        <p><a href="mailto:info@adbox.kz">info@adbox.kz</a></p>
                        <h3>Контакты</h3>
                        <p><a><i class="fa fa-phone"></i> +7 705 740 18 80</a></p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>МЫ в СОЦ СЕТЯХ</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Информация</h3>
                        <ul style="padding: 0px;">
                            <ui>
                               <a href="/faq">FAQ</a><br/>
                            </ui>
                            <ui>
                               <a href="/instructions">Инструкции</a><br/>
                            </ui>
                            <ui>
                               <a href="/conditions">Условия участия</a><br/>
                            </ui>
                            <ui>
                               <a href="/formats">Форматы</a><br/>
                            </ui>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; AdBox 2015
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visble-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>




</body>

</html>

templates/campaign_form.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block css %}
{% load humanize %}


{% endblock %}
{% block content %}
    <section style="padding-left: 15%;">
    <h1>Отправить заявку на создание кампании</h1>
    <form action="/campaign/new/" method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.campaign_name.errors }}
            <label for="id_campaign_name">Название кампании:</label><br>
            {{ form.campaign_name }}
        </div>
        <div class="fieldWrapper">
            {{ form.campaign_text.errors }}
            <label for="id_campaign_text">Описание кампании:</label><br>
            {{ form.campaign_text }}
        </div>
        <input type="submit" value="Отправить" class="btn btn-primary" />
    </form>
    </section>
{% endblock %}

templates/campaigns.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block css %}
{% load humanize %}


{% endblock %}
{% block content %}
    <section style="padding-left: 15%;">

    <!-- Include Required Prerequisites -->
    <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
    <span></span> <b class="caret"></b>
    </div>

<script type="text/javascript">
$(function() {

    $('#reportrange span').html(moment("{{ date_from }}").format('MMMM D, YYYY') + ' - ' + moment("{{ date_to }}").format('MMMM D, YYYY'));

    $('#reportrange').daterangepicker({
        format: 'MM/DD/YYYY',
        startDate: moment().subtract(29, 'days'),
        endDate: moment(),
        minDate: '01/01/2012',
        maxDate: '12/31/2015',
        showDropdowns: true,
        showWeekNumbers: true,
        timePicker: false,
        timePickerIncrement: 1,
        timePicker12Hour: true,
        ranges: {
           'Today': [moment(), moment()],
           'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Last 7 Days': [moment().subtract(6, 'days'), moment()],
           'Last 30 Days': [moment().subtract(29, 'days'), moment()],
           'This Month': [moment().startOf('month'), moment().endOf('month')],
           'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        opens: 'left',
        drops: 'down',
        buttonClasses: ['btn', 'btn-sm'],
        applyClass: 'btn-primary',
        cancelClass: 'btn-default',
        separator: ' to ',
        locale: {
            applyLabel: 'Submit',
            cancelLabel: 'Cancel',
            fromLabel: 'From',
            toLabel: 'To',
            customRangeLabel: 'Custom',
            daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            firstDay: 1
        }
    }, function(start, end, label) {
        window.location.replace('?start='+start.format('YYYY-MM-DD')+'&end='+end.format('YYYY-MM-DD'));
        console.log(start.toISOString(), end.toISOString(), label);
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
    });

});
</script>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#finances" aria-controls="home" role="tab" data-toggle="tab">Финансы</a></li>
        <li role="presentation"><a href="#sites" aria-controls="profile" role="tab" data-toggle="tab">Сайты</a></li>
    </ul>
  <div class="tab-content">
  {% for campaign_list in  campaign_list_array%}
      <div role="tabpanel" class="tab-pane active" id="finances">
        <h1>{{ campaign_list.name }}</h1>
      <table style="margin: auto auto;"
        <table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
            <th>Кликов</th>
            <th>Просмотров</th>
            <th>CTR</th>
            <th>Охват за последний месяц</th>
        </tr>
    </thead>
    <tbody>
        {% for campaign in campaign_list.campaign_set %}
        <tr>
            <td>{{ campaign.id }}</td>
            <td>{{ campaign.name }}</td>
            <td>{{ campaign.clicks }}</td>
            <td>{{ campaign.views }}</td>
            <td>{{ campaign.ctr|floatformat:3|intcomma }}</td>
            <td>{{ campaign.reach }}</td>
        </tr>
        {% endfor %}
        <tr class="active">
            <td colspan="2">Итого</td>
            <td>{{campaign_list.sum_of_campains.clicks}}</td>
            <td>{{campaign_list.sum_of_campains.views}}</td>
            <td>{{campaign_list.sum_of_campains.ctr|floatformat:3|intcomma}}</td>
            <td>{{campaign_list.sum_of_campains.reach}}</td>
        </tr>
    </tbody>
</table>
    </div>
  {% endfor %}
  </div>
    <br>
    <button class="btn btn-primary" onclick="location.href='/campaign/new'">Создать рекламную кампанию</button>
    </section>
{% endblock %}

templates/conditions.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
 <section ng-app="siteApp">
        <link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
     <link href="/static/css/profile.css" rel="stylesheet" type="text/css">
<div class="container">
        <h1>Условия использования</h1>
</div>
 </section>

{% endblock %}

templates/faq.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
 <section ng-app="siteApp">
        <link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
     <link href="/static/css/profile.css" rel="stylesheet" type="text/css">
<div class="container">
        <h1>FAQ</h1>
</div>
 </section>

{% endblock %}

templates/formats.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
 <section ng-app="siteApp">
        <link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
     <link href="/static/css/profile.css" rel="stylesheet" type="text/css">
<div class="container">
        <h1>Форматы</h1>
</div>
 </section>

{% endblock %}

templates/instructions.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
 <section ng-app="siteApp">
        <link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
     <link href="/static/css/profile.css" rel="stylesheet" type="text/css">
<div class="container">
        <h1>Инструкции</h1>
</div>
 </section>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}Welcome to Django{% endblock %}
{% block content %}
 <section ng-app="siteApp">
        <link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
     <link href="/static/css/profile.css" rel="stylesheet" type="text/css">
<div class="container">
        <h1>Спасибо за отправку заявки =)</h1>
</div>
 </section>

{% endblock %}